import type { Metadata } from "next";

//fonts
import { Playfair_Display } from "next/font/google";

//styles
import "./globals.css";

//components
import Navbar from "./components/navbar/Navbar";
import Footer from "./components/footer/Footer";

const playfair = Playfair_Display({
  subsets: ["latin"],
  // optionally you can add other options like weight, display, fallback
  variable: "--font-playfair-display",
  display: "swap", // ensures graceful loading :contentReference[oaicite:1]{index=1}
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={playfair.variable}>
      <body className="antialiased">
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
